<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="PropertyReference.xsl"?>
<!DOCTYPE properties [
<!--  <!ENTITY % DocBookDTD PUBLIC "-//OASIS//DTD DocBook V4.2//EN"
"/usr/share/sgml/docbook/dtd/4.2xml/docbookx.dtd">
 %DocBookDTD; -->
 <!ELEMENT properties (property*)>

 <!ELEMENT property (descr, attributes?, optattributes?,
                     seealso?, freestyle?, example? )>
 <!ATTLIST property
   name CDATA #REQUIRED
   id CDATA #REQUIRED
   inheritable (Yes|No) "No" 
   scenario (Yes|No) "No"
 >

 <!ELEMENT descr (para*)>
 <!ELEMENT attributes (attr*)>
 <!ELEMENT attr (para*)>
 <!ATTLIST attr
   name CDATA #REQUIRED
   type CDATA #REQUIRED
   list (0|1) "0"
   optional (0|1) "0"
 >

 <!ELEMENT optattributes (optattr*)>
 <!ELEMENT optattr (#PCDATA)>

 <!ELEMENT seealso (also*)>
 <!ELEMENT also (#PCDATA)>
 <!ELEMENT freestyle (para*)>
 <!ELEMENT example (#PCDATA)>

 <!ELEMENT para (#PCDATA|varname|link|simplelist|screen)*>
 <!ELEMENT varname (#PCDATA)*>
 <!ELEMENT link (#PCDATA)>
 <!ATTLIST link
   linkend CDATA #REQUIRED
 >
 <!ELEMENT simplelist (member)*>
 <!ATTLIST simplelist
   type CDATA #REQUIRED
   columns CDATA #REQUIRED
 >
 <!ELEMENT member (#PCDATA|para|varname|link)*>
 <!ELEMENT screen (#PCDATA)>
 
  <!ENTITY example_account SYSTEM
   "../../TestSuite/Syntax/Correct/Account.tjp">
  <!ENTITY example_allocate SYSTEM
   "../../TestSuite/Syntax/Correct/Allocate-1.tjp">
  <!ENTITY example_alternative SYSTEM
   "../../TestSuite/Syntax/Correct/Alternative.tjp">
  <!ENTITY example_booking SYSTEM
   "../../TestSuite/Syntax/Correct/Booking.tjp">
  <!ENTITY example_buffer SYSTEM
   "../../TestSuite/Syntax/Correct/Buffer.tjp">
  <!ENTITY example_columns SYSTEM
   "../../TestSuite/Syntax/Correct/Columns.tjp">
  <!ENTITY example_complete SYSTEM
   "../../TestSuite/Syntax/Correct/Complete.tjp">
  <!ENTITY example_criticalpath SYSTEM
   "../../TestSuite/Syntax/Correct/CriticalPath.tjp">
  <!ENTITY example_depends SYSTEM
   "../../TestSuite/Syntax/Correct/Depends1.tjp">
  <!ENTITY example_durations SYSTEM
   "../../TestSuite/Syntax/Correct/Durations.tjp">
  <!ENTITY example_efficiency SYSTEM
   "../../TestSuite/Syntax/Correct/Efficiency.tjp">
  <!ENTITY example_export SYSTEM
   "../../TestSuite/Syntax/Correct/Export.tjp">
  <!ENTITY example_extend SYSTEM
   "../../TestSuite/Syntax/Correct/CustomAttributes.tjp">
  <!ENTITY example_flags SYSTEM
   "../../TestSuite/Syntax/Correct/Flags.tjp">
  <!ENTITY example_gap SYSTEM
   "../../TestSuite/Syntax/Correct/Gap.tjp">
  <!ENTITY example_guireport SYSTEM
   "../../TestSuite/Syntax/Correct/GUIReport.tjp">
  <!ENTITY example_taskbarprefixpostfix SYSTEM
   "../../TestSuite/Syntax/Correct/TaskbarPrefixPostfix.tjp">
  <!ENTITY example_htmltaskreport SYSTEM
   "../../TestSuite/Syntax/Correct/HtmlTaskReport.tjp">
  <!ENTITY example_icalreport SYSTEM
   "../../TestSuite/Syntax/Correct/ICalReport.tjp">
  <!ENTITY example_include SYSTEM
   "../../TestSuite/Syntax/Correct/Include2.tjp">
  <!ENTITY example_journalentry SYSTEM
   "../../TestSuite/Syntax/Correct/Journal.tjp">
  <!ENTITY example_limits SYSTEM
   "../../TestSuite/Syntax/Correct/Limits-1.tjp">
  <!ENTITY example_mandatory SYSTEM
   "../../TestSuite/Syntax/Correct/Mandatory.tjp">
  <!ENTITY example_milestone SYSTEM
   "../../TestSuite/Syntax/Correct/Milestone.tjp">
  <!ENTITY example_minmax SYSTEM
   "../../TestSuite/Syntax/Correct/MinMax.tjp">
  <!ENTITY example_numberformat SYSTEM
   "../../TestSuite/Syntax/Correct/Numberformat.tjp">
  <!ENTITY example_period SYSTEM
   "../../TestSuite/Syntax/Correct/Period.tjp">
  <!ENTITY example_persistent SYSTEM
   "../../TestSuite/Syntax/Correct/Persistent.tjp">
  <!ENTITY example_precedes SYSTEM
   "../../TestSuite/Syntax/Correct/Precedes1.tjp">
  <!ENTITY example_priority SYSTEM
   "../../TestSuite/Syntax/Correct/Priority.tjp">
  <!ENTITY example_project SYSTEM
   "../../TestSuite/Syntax/Correct/Project.tjp">
  <!ENTITY example_projectids SYSTEM
   "../../TestSuite/Syntax/Correct/ProjectIDs.tjp">
  <!ENTITY example_reports SYSTEM
   "../../TestSuite/Syntax/Correct/Reports.tjp">
  <!ENTITY example_resource SYSTEM
   "../../TestSuite/Syntax/Correct/Resource.tjp">
  <!ENTITY example_responsible SYSTEM
   "../../TestSuite/Syntax/Correct/Responsible.tjp">
  <!ENTITY example_scenario SYSTEM
   "../../TestSuite/Syntax/Correct/Scenario.tjp">
  <!ENTITY example_scheduling SYSTEM
   "../../TestSuite/Syntax/Correct/Scheduling.tjp">
  <!ENTITY example_select SYSTEM
   "../../TestSuite/Syntax/Correct/Select.tjp">
  <!ENTITY example_shift SYSTEM
   "../../TestSuite/Syntax/Correct/Shift.tjp">
  <!ENTITY example_simple SYSTEM
   "../../TestSuite/Syntax/Correct/Simple.tjp">
  <!ENTITY example_supplement SYSTEM
   "../../TestSuite/Syntax/Correct/Supplement.tjp">
  <!ENTITY example_taskroot SYSTEM
   "../../TestSuite/Syntax/Correct/TaskRoot.tjp">
  <!ENTITY example_timezone SYSTEM
   "../../TestSuite/Syntax/Correct/Timezone.tjp">
  <!ENTITY example_vacation SYSTEM
   "../../TestSuite/Syntax/Correct/Vacation.tjp">
  <!ENTITY example_xmlreport SYSTEM
   "../../TestSuite/Syntax/Correct/XMLReport.tjp">
]>

<properties>
 <property name="The TJP File" id="global_scope">
 <descr><para>All TaskJuggler project files should start with the
project property and must contain at least one task definition. To
visualize the results of the scheduling process, at least one of the
reports should be specified.</para></descr>
 <optattributes>
   <optattr>account</optattr>
   <optattr>copyright</optattr>
   <optattr>csvaccountreport</optattr>
   <optattr>csvresourcereport</optattr>
   <optattr>csvtaskreport</optattr>
   <optattr>export</optattr>
   <optattr>flags_declare</optattr>
   <optattr>htmlaccountreport</optattr>
   <optattr>htmlresourcereport</optattr>
   <optattr>htmlstatusreport</optattr>
   <optattr>htmltaskreport</optattr>
   <optattr>htmlmonthlycalendar</optattr>
   <optattr>htmlweeklycalendar</optattr>
   <optattr>include</optattr>
   <optattr>macro</optattr>
   <optattr>maxeffort</optattr>
   <optattr>limits</optattr>
   <optattr>priority</optattr>
   <optattr>projectid</optattr>
   <optattr>projectids</optattr>
   <optattr>project</optattr>
   <optattr>rate</optattr>
   <optattr>resource</optattr>
   <optattr>shift</optattr>
   <optattr>supplement</optattr>
   <optattr>task</optattr>
   <optattr>vacation_global</optattr>
   <optattr>xmlreport</optattr>
  </optattributes>
  <example>&example_simple;</example>
 </property>
 <property name="account" id="account">
  <descr><para>Declares an account. Accounts can be used to calculate costs
of tasks or the whole project. Account declaration may be nested, but
only the top level accounts may have a type attribute specified. An
account that has sub-accounts may not have a <link
linkend="PROPERTY_credit">credit</link>.  sub-accounts inherit
this type.</para></descr>
  <attributes>
   <attr name="id" type="ID">
    <para>Each account must have a unique ID.</para>
   </attr> 
   <attr name="name" type="STRING"/>
   <attr name="type" type="ID" optional="1">
    <para>The type may be <varname>cost</varname> or
<varname>revenue</varname>.</para></attr>
  </attributes>
  <optattributes>
   <optattr>account</optattr>
   <optattr>credit</optattr>
  </optattributes>
  <seealso>
   <also>csvaccountreport</also>
   <also>htmlaccountreport</also>
  </seealso>
  <example>&example_account;</example>
 </property>
 <property name="account" id="account_task" inheritable="Yes">
  <descr><para>All amounts associated with the task will be credited
to the specified account. The account must not be an account group.
</para></descr>
  <attributes>
   <attr name="accountid" type="ID"/>
  </attributes>
  <seealso>
   <also>account</also>
  </seealso>
  <example>&example_account;</example>
 </property>
 <property name="accumulate" id="accumulate" inheritable="No">
  <descr><para>If this attribute is specified the values in the calendar
columns are accumulated over the reported interval.</para></descr>
  <example>&example_account;</example>
 </property>
 <property name="allowredefinition" id="allowredefinition" inheritable="No">
  <descr><para>If this attribute is specified, redefinitions of task,
resources or accounts are not flagged as errors. The primary use of
this attribute is for projects that are created by merging sub projects
which are again the result of sub project merging. In certain
situations enclosing tasks, accounts or resources can be included in more
than one sub project. This attribute then avoids the error message which is
in most other cases a real user error. So use this feature with care
as real errors might go undetected.</para>

<para>In case attributes of the same property must be specified in two
different locations the <link linkend="PROPERTY_supplement">supplement</link>
construct is the recommended way to do this.</para></descr>
 </property>
 <property name="allocate" id="allocate" inheritable="Yes">
  <descr><para>Specify which resources should be allocated to the
task. The optional attributes provide numerous ways to control which
resource is used and when exactly it will be assigned to the task.
Shifts and limits can be used to restrict the allocation to certain
time intervals or to limit them to a certain maximum per time period.
</para></descr>
  <attributes>
   <attr name="resource" type="ID"/>
  </attributes>
  <optattributes>
   <optattr>alternative</optattr>
   <optattr>limits</optattr>
   <optattr>mandatory</optattr>
   <optattr>persistent</optattr>
   <optattr>purge</optattr>
   <optattr>select</optattr>
   <optattr>shift_selection</optattr>
  </optattributes>
  <seealso>
   <also>effort</also>
  </seealso>
  <example>&example_allocate;</example>
 </property>
 <property name="alternative" id="alternative" inheritable="No">
  <descr><para>A list of alternative resources for an allocation.
  There is no difference between the allocated resource and its
  alternatives. If no selection criteria is given, TaskJuggler picks
  the resource that it finds most appropriate.</para></descr>
  <attributes>
   <attr name="resource" type="ID" list="1"/>
  </attributes>
  <seealso>
   <also>select</also>
  </seealso>
  <example>&example_alternative;</example>
 </property>
 <property name="barlabels" id="barlabels" inheritable="No">
  <descr><para>Specifies the contents of the Gantt chart like bars in
HTML calendar columns. The default is to show load values.</para></descr>
  <attributes>
   <attr name="mode" type="ID">
    <para>See table below for possible values.</para>
   </attr>
  </attributes>
  <seealso>
   <also>columns</also>
   <also>showprojectids</also>
  </seealso>
  <freestyle>
   <para><simplelist type="horiz" columns="2">
   
   <member><varname>empty</varname></member>
   <member>Do not show any values on calendar bars.</member>
   
   <member><varname>load</varname></member>
   <member>Show task or resource load on calendar bars.</member>
   
   </simplelist></para>
  </freestyle>
 </property>
 <property name="baseline" id="baseline" inheritable="Yes"
 scenario="Yes">
  <descr><para>Disables the projection mode for the scenario. This is
  the default for the top-level scenario. In baseline mode it is
  assumed that no bookings are provided for any task.</para></descr>
  <seealso>
   <also>projection</also>
  </seealso>
 </property>
 <property name="booking" id="booking" inheritable="No" scenario="Yes">
  <descr><para>The booking attribute can be used to report completed
  work. This can be part of the necessary effort or the whole effort.
  When the scenario is scheduled in projection mode, TaskJuggler
  assumes that only the work reported with bookings has been done up
  to now. It then schedules a plan for the still missing effort.</para>
  <para>This attribute is also used within export reports to describe
  the details of a scheduled project.</para>
  <para>The sloppy attribute can be used when you want to skip
  non-working time or other allocations automatically. If it's not
  given, all bookings must only cover working time for the
  resource.</para></descr>
  <attributes>
   <attr name="task" type="ID"/>
   <attr name="period" type="DATEINTERVAL" list="1"/>
  </attributes>
  <optattributes>
   <optattr>overtime</optattr>
   <optattr>sloppy</optattr>
  </optattributes>
  <seealso>
   <also>complete</also>
   <also>projection</also>
   <also>sloppy_projection</also>
   <also>strict</also>
  </seealso>
  <example>&example_booking;</example>
 </property>
 <property name="caption" id="caption" inheritable="No">
  <descr><para>Specifies the caption used for a report table.</para></descr>
  <attributes>
   <attr name="text" type="STRING"/>
  </attributes>
  <seealso>
   <also>complete</also>
   <also>copyright</also>
   <also>headline</also>
  </seealso>
  <example>&example_htmltaskreport;</example>
 </property>
 <property name="celltext" id="celltext" inheritable="No">
  <descr><para>Specifies an alternative text that is used for all
cells of the column. Usually such a text contains a runtime macro,
otherwise all cells of the column will have the same fixed value.</para></descr>
  <attributes>
   <attr name="text" type="STRING"/>
  </attributes>
  <seealso>
   <also>cellurl</also>
  </seealso>
  <example>&example_columns;</example>
 </property>
 <property name="cellurl" id="cellurl" inheritable="No">
  <descr><para>Specifies an URL that is attached to the cell contents
of the cells of the column in HTML reports.</para></descr>
  <attributes>
   <attr name="url" type="STRING"/>
  </attributes>
  <seealso>
   <also>celltext</also>
  </seealso>
  <example>&example_columns;</example>
 </property>
 <property name="columns" id="columns" inheritable="No">
  <descr><para>Specifies which columns shall be included in a
report.</para>

<para>All columns support macro expansion. Contrary to the normal
macro expansion, these macros are expanded during the report
generation. So the value of the macro is being changed after each
table cell or table line. Consequently only build in macros can be
used. To protect the macro calls against expansion during the initial
file processing, the report macros must be prefixed with an additional
<varname>$</varname>.</para></descr>
  <attributes>
   <attr name="columnid" type="ID" list="1">
    <para>See table below for possible values.</para>
   </attr>
  </attributes>
  <optattributes>
   <optattr>celltext</optattr>
   <optattr>cellurl</optattr>
   <optattr>hidecelltext</optattr>
   <optattr>hidecellurl</optattr>
   <optattr>subtitle</optattr>
   <optattr>subtitleurl</optattr>
   <optattr>title</optattr>
   <optattr>titleurl</optattr>
  </optattributes>
  <freestyle>
   <para><simplelist type="horiz" columns="2">
   
   <member><varname>accounts</varname></member>
   <member>This columns lists the account that is assigned to the
	   respective task. It is called 'accounts' because later
	   versions will have support for multiple accounts.</member>
   
   <member><varname>chart</varname></member>
   <member>Use this column to get Gantt and resource charts. It's only
   supported by the interactive reports in the GUI.</member>
   
   <member><varname>completed</varname></member>
   <member>The percentage the task has been completed already. This is
   either the value specified by <link
   linkend="PROPERTY_complete">complete</link> or a value computed according
   to the current date (or the date specified by <link
   linkend="PROPERTY_now">now</link>) and the length, duration or
   effort.</member>
   
   <member><varname>completedeffort</varname></member>
   <member>The effort of a task that has already been completed.</member>
   
   <member><varname>cost</varname></member>
   <member>The accumulated costs of the task and its sub tasks</member>
   
   <member><varname>criticalness</varname></member>
   <member>The criticalness of the task. It is a measure for the
   probability that an effort task gets the requested resources
   early.</member>
   
   <member><varname>daily</varname></member>
   <member>A day-by-day calendar view of the tasks</member>
   
   <member><varname>depends</varname></member>
   <member>The task index of the tasks on which this task
   depends</member>
   
   <member><varname>duration</varname></member>
   <member>The duration of the task</member>
   
   <member><varname>efficiency</varname></member>
   <member>The efficiency of the resource. It's a measurement of how
   much the resource can contribute to the workload of tasks.</member>
   
   <member><varname>effort</varname></member>
   <member>The effort put into the task</member>
   
   <member><varname>end</varname></member>
   <member>The end date of a task</member>
   
   <member><varname>endbuffer</varname></member>
   <member>The percentage of the endbuffer</member>
   
   <member><varname>endbufferstart</varname></member>
   <member>The start time of the end buffer</member>
   
   <member><varname>flags</varname></member>
   <member>The list of flags assigned to the task or resource</member>
   
   <member><varname>follows</varname></member>
   <member>The task index of the tasks that depend on this task</member>
   
   <member><varname>freeload</varname></member>
   <member>The workload of the resource that has not been allocated.</member>
   
   <member><varname>hierarchindex</varname></member>
   <member>The hierarchical index of a task. The index is calculated from the
   hierarchical structure of the list as well as the start and end dates.
   </member>
   
   <member><varname>hierarchno</varname></member>
   <member>The hierarchical number of a task. It is based on the order of
   declaration.</member>
   
   <member><varname>id</varname></member>
   <member>The global ID of a task</member>
   
   <member><varname>index</varname></member>
   <member>The index of a task. The index is calculated from the
   hierarchical structure of the list as well as the start and end dates.
   </member>
   
   <member><varname>maxeffort</varname></member>
   <member>The maximum daily load wanted for the resource</member>
   
   <member><varname>maxend</varname></member>
   <member>The latest desired end date</member>
   
   <member><varname>maxstart</varname></member>
   <member>The latest desired start date</member>
   
   <member><varname>mineffort</varname></member>
   <member>The minimum daily load wanted for the resource</member>
   
   <member><varname>minend</varname></member>
   <member>The earliest desired end date</member>
   
   <member><varname>minstart</varname></member>
   <member>The earliest desired start date</member>
   
   <member><varname>monthly</varname></member>
   <member>A month-by-month calendar view of the tasks</member>
   
   <member><varname>name</varname></member>
   <member>The name of a task, resource, or account</member>
   
   <member><varname>no</varname></member>
   <member>The task index in the list. It starts with 1 and increases for
   every listed item by 1.</member>
   
   <member><varname>note</varname></member>
   <member>The description of the task</member>
   
   <member><varname>pathcriticalness</varname></member>
   <member>The overall criticalness of the task. It is a measure for the
   probability that an effort task gets scheduled as early as
   possible. The tasks of the most critical path have the highest path
   criticalness.</member>
   
   <member><varname>priority</varname></member>
   <member>The scheduling priority</member>
   
   <member><varname>profit</varname></member>
   <member>The accumulated profit of the task and its sub tasks</member>
   
   <member><varname>projectid</varname></member>
   <member>The project ID of the task</member>
   
   <member><varname>projectids</varname></member>
   <member>The project IDs of the projects a resource is allocated to</member>
   
   <member><varname>quarterly</varname></member>
   <member>A quarter-by-quarter calendar view of the tasks</member>
   
   <member><varname>rate</varname></member>
   <member>The daily rate of the resource</member>
   
   <member><varname>reference</varname></member>
   <member>A reference to a URL that contains further information.</member>
   
   <member><varname>remainingeffort</varname></member>
   <member>The effort of a task that still needs to be done to
   complete the task..</member>
   
   <member><varname>resources</varname></member>
   <member>The names of the used resources</member>
   
   <member><varname>responsibilities</varname></member>
   <member>A list of all tasks indices for which a resource is
   responsible </member>
   
   <member><varname>responsible</varname></member>
   <member>The name of the resource responsible for a task</member>
   
   <member><varname>revenue</varname></member>
   <member>The accumulated revenue of the task and its sub tasks</member>
   
   <member><varname>scenario</varname></member>
   <member>The name of the scenario. This column is helpful when multiple
   scenarios are shown in the table. See also <link
   linkend="PROPERTY_scenarios">scenarios</link>.</member>
   
   <member><varname>schedule</varname></member>
   <member>A detailed schedule of the allocations for the resource.</member>
   
   <member><varname>scheduling</varname></member>
   <member>The scheduling direction of the task. ASAP (As Soon As
   Possible) tasks are scheduled from start to end, ALAP (As Late As
   Possible) are scheduled from end to start.</member>
   
   <member><varname>seqno</varname></member>
   <member>The task index in the order of declaration. Each
   time a task declaration is completed, the sequence number is increased
   by 1. </member>
   
   <member><varname>start</varname></member>
   <member>The start date of a task</member>
   
   <member><varname>startbuffer</varname></member>
   <member>The percentage of the start buffer</member>
   
   <member><varname>startbufferend</varname></member>
   <member>The end time of the start buffer</member>
   
   <member><varname>status</varname></member>
   <member>The current status of the task. This is derived from the
   current date or the date specified by <link
   linkend="PROPERTY_now">now</link> and the degree of completion. The
   degree of completion is either computed or has been specified by <link
   linkend="PROPERTY_complete">complete</link>.</member>
  
   <member><varname>statusnote</varname></member>
   <member>Some comment about the current status of the task.</member>
   
   <member><varname>total</varname></member>
   <member>Total accumulated values</member>
   
   <member><varname>utilization</varname></member>
   <member>The ratio between the allocated work load of the resource
   and it's overall available work load.</member>
   
   <member><varname>weekly</varname></member>
   <member>A week-by-week calendar view of the tasks</member>
   
   <member><varname>yearly</varname></member>
   <member>A year-by-year calendar view of the tasks</member>
   
   </simplelist></para>
<para>The following macros are supported for normal table cells:</para>

<para><simplelist type="horiz" columns="2">
<member><varname>$${0}</varname></member>
<member>This is the original value of the table cell. This macro is
useful if the user would like to extend the cell text with a fixed
string.</member>

<member><varname>$${accountid}</varname></member>
<member>The ID of the account.</member>

<member><varname>$${resourceid}</varname></member>
<member>The ID of the resource.</member>

<member><varname>$${taskid}</varname></member> <member>the
id of the task.</member>

</simplelist></para>

<para>Additionally the original contents of other cells of the same
report line can be accessed by the column ID. The following columns
are supported:</para>

<para><varname>index, no, hierarchindex, hierarchno, id,
name</varname></para>

<para>For the title or sub title of the calendar columns
(<varname>daily, weekly, monthly, quarterly, yearly</varname>) the
following macros are supported:</para>

<para><varname>$${day}, $${month}, $${week}, $${quarter},
$${year}</varname>.</para>
  </freestyle>
  <example>&example_columns;</example>
 </property>
 <property name="complete" id="complete" inheritable="No"
scenario="Yes">
  <descr><para>Specifies what percentage of the task is already
completed. This can be useful for project tracking. Reports with
calendar elements may show the completed part of the task in a
different color. The completion percentage has no impact on the
scheduler. It's meant for documentation purposes only.</para>

<para>Tasks may not have subtasks if this attribute is used.</para></descr>
  <attributes>
   <attr name="percent" type="INTEGER">
    <para>The value must be between 0 and 100.</para>
   </attr>
  </attributes>
  <example>&example_complete;</example>
  <seealso>
   <also>booking</also>
  </seealso>
 </property>
 <property name="copyright" id="copyright" inheritable="No">
  <descr><para>Adds a copyright notice to all subsequently defined
reports. This notice may contain any text. The notice is added at the
bottom of the report.</para></descr>
  <attributes>
   <attr name="text" type="STRING"/>
  </attributes>
  <seealso>
   <also>headline</also>
   <also>caption</also>
  </seealso>
  <example>&example_htmltaskreport;</example>
 </property>
 <property name="credit" id="credit">
  <descr><para>Credits the specified amount to the account at the
specified date. The description should contain some information about
the reason for the transaction.</para></descr>
  <attributes>
   <attr name="date" type="DATE"/>
   <attr name="description" type="STRING"/>
   <attr name="amount" type="REAL"/>
  </attributes>
  <example>&example_account;</example>
 </property>
 <property name="csvaccountreport" id="csvaccountreport">
  <descr><para>The report lists all specified account values as a comma
separated list. This is useful to export TaskJuggler data to Office
Suites like OpenOffice.org or KOffice.</para></descr>
  <attributes>
   <attr name="filename" type="STRING"/>
  </attributes>
  <optattributes>
   <optattr>accumulate</optattr>
   <optattr>columns</optattr>
   <optattr>end_report</optattr>
   <optattr>rollupaccount</optattr>
   <optattr>hideaccount</optattr>
   <optattr>period_report</optattr>
   <optattr>scenario_report</optattr>
   <optattr>separator</optattr>
   <optattr>sortaccounts</optattr>
   <optattr>start_report</optattr>
  </optattributes>
  <seealso>
   <also>htmlaccountreport</also>
  </seealso>
 </property>
 <property name="csvresourcereport" id="csvresourcereport" inheritable="No">
  <descr><para>The report lists all specified resource values as a
comma separated list. This is useful to export TaskJuggler data to
Office Suites like OpenOffice.org or KOffice.</para></descr>
  <attributes>
   <attr name="filename" type="STRING"/>
  </attributes>
  <optattributes>
   <optattr>columns</optattr>
   <optattr>end_report</optattr>
   <optattr>rollupresource</optattr>
   <optattr>hideresource</optattr>
   <optattr>loadunit</optattr>
   <optattr>period_report</optattr>
   <optattr>scenario_report</optattr>
   <optattr>separator</optattr>
   <optattr>shorttimeformat</optattr>
   <optattr>sortresources</optattr>
   <optattr>start_report</optattr>
   <optattr>timeformat</optattr>
  </optattributes>
  <seealso>
   <also>htmlresourcereport</also>
   <also>resourcereport</also>
  </seealso>
 </property>
 <property name="csvtaskreport" id="csvtaskreport" inheritable="No">
  <descr><para>The report lists all specified task values as a comma
separated list. This is useful to export TaskJuggler data to Office
Suites like OpenOffice.org or KOffice.</para></descr>
  <attributes>
   <attr name="filename" type="STRING"/>
  </attributes>
  <optattributes>
   <optattr>columns</optattr>
   <optattr>end_report</optattr>
   <optattr>rolluptask</optattr>
   <optattr>hidetask</optattr>
   <optattr>loadunit</optattr>
   <optattr>period_report</optattr>
   <optattr>scenario_report</optattr>
   <optattr>separator</optattr>
   <optattr>shorttimeformat</optattr>
   <optattr>sorttasks</optattr>
   <optattr>start_report</optattr>
   <optattr>taskroot</optattr>
   <optattr>timeformat</optattr>
  </optattributes>
  <seealso>
   <also>htmltaskreport</also>
   <also>taskreport</also>
  </seealso>
 </property>
 <property name="currency" id="currency" inheritable="No">
  <descr><para>The default currency unit.</para></descr>
  <attributes>
   <attr name="text" type="STRING"/>
  </attributes>
  <seealso>
   <also>currencyformat</also>
  </seealso>
  <example>&example_account;</example>
 </property>
 <property name="currencyformat" id="currencyformat" inheritable="Yes">
  <descr><para>These values specify the default format used for all
currency values. The <varname>negativeprefix</varname> and
<varname>negativesuffix</varname> strings enclose negative currency
values. The <varname>thousandseparator</varname> can be used to make
large numbers more readable. The <varname>fractionseparator</varname>
separates the fractional part from the rest.
<varname>fractiondigits</varname> specifies how many fractional digits
should be shown at a maximum.</para></descr>
  <attributes>
   <attr name="negativeprefix" type="STRING"/>
   <attr name="negativesuffix" type="STRING"/>
   <attr name="thousandseparator" type="STRING"/>
   <attr name="fractionseparator" type="STRING"/>
   <attr name="fractiondigits" type="INTEGER"/>
  </attributes>
  <seealso>
   <also>currency</also>
  </seealso>
  <example>&example_numberformat;</example>
 </property>
 <property name="dailymax" id="dailymax" inheritable="Yes">
  <descr><para>Sets the daily limit of a resource usage or a resource
allocation to a task.</para></descr>
  <attributes>
   <attr name="value" type="REAL"/>
   <attr name="unit" type="UNIT"/>
  </attributes>
  <seealso>
   <also>monthlymax</also>
   <also>weeklymax</also>
   <also>yearlymax</also>
   <also>projectmax</also>
  </seealso>
  <example>&example_limits;</example>
 </property>